version: '3'
services:
  test-api:
    build: .
    depends_on:
      - mongodb
    ports:
      - 8000:8000
  mongodb:
    hostname: database
    container_name: mongo-database
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - ./data/db:/usr/data/db
    command: mongod
networks:
  tiered: